Update grub-mkfont.c
Possible fix for bug in build
  util/grub-mkfont.c:36:30: fatal error: freetype/ftsynth.h: No such file or directory.

Bug noted in AUR comments at https://aur.archlinux.org/packages/burg-bios-bzr

Can't find a custom ftsynth.h file in repo, assuming typo.